# Generated by Django 3.1.4 on 2020-12-27 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre completo')),
                ('birth_date', models.DateField(verbose_name='Fecha de nacimiento')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Nombre categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('published', models.DateField(blank=True, null=True, verbose_name='Publicado')),
                ('rented', models.BooleanField(blank=True, default=False, null=True, verbose_name='Rentado')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='book.author', verbose_name='Autor')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='book.category', verbose_name='Categoría')),
            ],
        ),
    ]
