# Generated by Django 3.1.4 on 2020-12-29 04:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lease_date', models.DateField(verbose_name='Fecha de arriendo')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='book.book', verbose_name='Libro')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Lector')),
            ],
        ),
    ]
