# Generated by Django 3.1.4 on 2020-12-29 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20201229_1455'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DetailBook',
        ),
    ]
