# Generated by Django 3.1.4 on 2020-12-31 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_rentbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentbook',
            name='date_return',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentbook',
            name='rented',
            field=models.BooleanField(default=False),
        ),
    ]
