# Generated by Django 3.1.4 on 2021-01-04 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_auto_20201231_0237'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='stock',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Stock'),
        ),
    ]
