# Generated by Django 3.1.4 on 2021-01-04 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_book_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='rented',
        ),
    ]
